export const foodMenuItems: MenuItem[] = [
  {
    itemId: "1",
    name: "B.L.T.",
    price: 7.95,
    station: "salad",
    ingredients: [
      { ingredient: "White bread", selected: true },
      { ingredient: "Butter", selected: true },
      { ingredient: "Bacon", selected: true },
      { ingredient: "Lettuce", selected: true },
      { ingredient: "Tomato", selected: true },
    ],
  },
  {
    itemId: "2",
    name: "Bacon Cheese Burger",
    station: "grill",
    price: 13.95,
    ingredients: [
      { ingredient: "Bacon", selected: true },
      { ingredient: "Cheese", selected: true },
      { ingredient: "Ketchup", selected: true },
      { ingredient: "Fried onions", selected: true },
      { ingredient: "Lettuce", selected: true },
      { ingredient: "Tomato", selected: true },
    ],
  },

  {
    itemId: "3",
    name: "Caesar salad",
    station: "salad",
    price: 12.95,
    ingredients: [
      { ingredient: "Chicken", selected: true },
      { ingredient: "Bacon", selected: true },
      { ingredient: "Parmesan", selected: true },
      { ingredient: "Lettuce", selected: true },
      { ingredient: "Croutons", selected: true },
    ],
  },
  {
    itemId: "4",
    name: "Waldorf salad",
    price: 12.95,
    station: "salad",
    ingredients: [
      { ingredient: "Apple", selected: true },
      { ingredient: "Grapes", selected: true },
      { ingredient: "Celery", selected: true },
      { ingredient: "Walnuts", selected: true },
      { ingredient: "Lettuce", selected: true },
    ],
  },

  {
    itemId: "5",
    name: "Club sandwich",
    station: "salad",
    price: 9.95,
    ingredients: [
      { ingredient: "White bread", selected: true },
      { ingredient: "Mayo", selected: true },
      { ingredient: "Chicken", selected: true },
      { ingredient: "Bacon", selected: true },
      { ingredient: "Lettuce", selected: true },
      { ingredient: "Tomato", selected: true },
    ],
  },
  {
    itemId: "6",
    name: "Cod",
    station: "fry",
    price: 12.5,
    ingredients: [
      { ingredient: "Mushy peas", selected: true },
      { ingredient: "Lemon", selected: true },
      { ingredient: "Side salad", selected: true },
    ],
  },
  {
    itemId: "7",
    name: "Regular burger",
    station: "grill",
    price: 9.95,
    ingredients: [
      { ingredient: "Ketchup", selected: true },
      { ingredient: "Onion", selected: true },
    ],
  },
  {
    itemId: "8",
    name: "Salmon",
    station: "grill",
    price: 13.95,
    ingredients: [
      { ingredient: "Dill sauce", selected: true },
      { ingredient: "Lemon", selected: true },
    ],
  },
  {
    itemId: "9",
    name: "Steak sandwich",
    station: "grill",
    price: 15.95,
    ingredients: [
      { ingredient: "Fried onions", selected: true },
      { ingredient: "Lettuce", selected: true },
      { ingredient: "Tomato", selected: true },
      { ingredient: "Side salad", selected: true },
      { ingredient: "Mushrooms", selected: true },
    ],
  },

  {
    itemId: "10",
    name: "Toasted Special",
    station: "salad",
    price: 7.95,
    ingredients: [
      { ingredient: "White bread", selected: true },
      { ingredient: "Butter", selected: true },
      { ingredient: "Ham", selected: true },
      { ingredient: "Cheese", selected: true },
      { ingredient: "Tomato", selected: true },
      { ingredient: "Onion", selected: true },
    ],
  },

  {
    itemId: "11",
    name: "Vol Au Vont",
    station: "expeditor",
    price: 11.5,
    ingredients: [
      { ingredient: "Pastry", selected: true },
      { ingredient: "Side salad", selected: true },
    ],
  },
  {
    itemId: "12",
    name: "Lamb Shank",
    station: "grill",
    price: 14.9,
    ingredients: [{ ingredient: "Gravy", selected: true }],
  },
  {
    itemId: "13",
    name: "8 oZ Steak",
    station: "grill",
    price: 19.95,
    ingredients: [
      { ingredient: "Pepper sauce", selected: true },
      { ingredient: "Onion rings", selected: true },
    ],
  },

  {
    itemId: "14",
    name: "Chicken wings",
    station: "fry",
    price: 8.95,
    ingredients: [
      { ingredient: "Blue cheese dip", selected: true },
      { ingredient: "Celery", selected: true },
      { ingredient: "Side salad", selected: true },
    ],
  },

  {
    itemId: "15",
    name: "Shepherd pie",
    price: 14.95,
    station: "expeditor",
    ingredients: [{ ingredient: "Peas", selected: true }],
  },

  {
    itemId: "16",
    name: "Fried Brie",
    price: 8.95,
    station: "fry",
    ingredients: [{ ingredient: "Side salad", selected: true }],
  },
  {
    itemId: "17",
    name: "Roast chicken",
    price: 17.95,
    station: "expeditor",
    ingredients: [
      { ingredient: "Gravy", selected: true },
      { ingredient: "Coleslaw", selected: true },
      { ingredient: "Stuffing", selected: true },
    ],
  },
  {
    itemId: "18",
    name: "Chicken Curry",
    price: 14.95,
    station: "expeditor",
    ingredients: [{ ingredient: "Rice", selected: true }],
  },
  {
    itemId: "19",
    name: "Beef Stroganoff",
    price: 13.95,
    station: "expeditor",
    ingredients: [{ ingredient: "Rice", selected: true }],
  },
  {
    itemId: "20",
    name: "Lasagna",
    price: 14.95,
    station: "expeditor",
    ingredients: [{ ingredient: "Side salad", selected: true }],
  },
  {
    itemId: "21",
    name: "Roast Vegetables",
    price: 4.0,
    station: "expeditor",
    ingredients: [],
  },
  {
    itemId: "22",
    name: "Soup of the day",
    station: "expeditor",
    price: 4.95,
    ingredients: [],
  },
  {
    itemId: "23",
    name: "Baked Potato",
    price: 11.95,
    station: "expeditor",
    ingredients: [
      { ingredient: "Sour cream", selected: true },
      { ingredient: "Cheese", selected: true },
      { ingredient: "Bacon", selected: true },
    ],
  },
  {
    itemId: "24",
    name: "Chips",
    station: "fry",
    price: 3.7,
    ingredients: [],
  },
];

export const drinkMenuItems: MenuItem[] = [
  {
    itemId: "101",
    name: "Coke",
    price: 3.4,
    ingredients: [],
    station: "bar",
  },
  {
    itemId: "102",
    name: "Diet coke",
    price: 3.4,
    ingredients: [],
    station: "bar",
  },
  {
    itemId: "103",
    name: "7up",
    price: 3.4,
    ingredients: [],
    station: "bar",
  },
  {
    itemId: "104",
    name: "Club orange",
    price: 3.4,
    ingredients: [],
    station: "bar",
  },

  {
    itemId: "105",
    name: "Ameri cano",
    price: 2.9,
    ingredients: [],
    station: "bar",
  },
  {
    itemId: "106",
    name: "Latte",
    price: 3.2,
    ingredients: [],
    station: "bar",
  },
  {
    itemId: "107",
    name: "Cappa chino",
    price: 3.4,
    ingredients: [],
    station: "bar",
  },
  {
    itemId: "108",
    name: "Flat white",
    price: 3.4,
    ingredients: [],
    station: "bar",
  },
  {
    itemId: "109",
    name: "Espresso",
    price: 2.6,
    ingredients: [],
    station: "bar",
  },

  {
    itemId: "110",
    name: "Pt Guinness",
    price: 5.1,
    ingredients: [],
    station: "bar",
  },
  {
    itemId: "111",
    name: "Pt Heineken",
    price: 5.8,
    ingredients: [],
    station: "bar",
  },
  {
    itemId: "112",
    name: "Pt Budwieser",
    price: 5.8,
    ingredients: [],
    station: "bar",
  },
  {
    itemId: "113",
    name: "Pt Carlsberg",
    price: 5.8,
    ingredients: [],
    station: "bar",
  },
  {
    itemId: "114",
    name: "Pt Bulmers",
    price: 5.8,
    ingredients: [],
    station: "bar",
  },
  {
    itemId: "115",
    name: "Gordons Gin",
    price: 5.2,
    ingredients: [],
    station: "bar",
  },
  {
    itemId: "116",
    name: "Vodka",
    price: 5.1,
    ingredients: [],
    station: "bar",
  },
  {
    itemId: "117",
    name: "Cpt Morgans",
    price: 5.4,
    ingredients: [],
    station: "bar",
  },
  {
    itemId: "118",
    name: "Bacardi",
    price: 5.2,
    ingredients: [],
    station: "bar",
  },
  {
    itemId: "119",
    name: "Vodka",
    price: 5.1,
    ingredients: [],
    station: "bar",
  },
  {
    itemId: "120",
    name: "Cab sauvignon",
    price: 5.9,
    ingredients: [],
    station: "bar",
  },
  {
    itemId: "121",
    name: "Pinot Grigio",
    price: 5.9,
    ingredients: [],
    station: "bar",
  },
  {
    itemId: "122",
    name: "Merlot",
    price: 5.8,
    ingredients: [],
    station: "bar",
  },
  {
    itemId: "123",
    name: "Sauv blanc",
    price: 5.6,
    ingredients: [],
    station: "bar",
  },
  {
    itemId: "124",
    name: "Malbec",
    price: 6.1,
    ingredients: [],
    station: "bar",
  },
];

export const ingredientsList: Ingredient[] = [
  "Butter",
  "Mayo",
  "White bread",
  "Lettuce",
  "Tomato",
  "Cheese",
  "Onion",
  "Bacon",
  "Chicken",
  "Ham",
  "Pepper sauce",
  "Onion rings",
  "Ketchup",
  "Fried onions",
  "Parmesan",
  "Croutons",
  "Blue cheese dip",
  "Side salad",
  "Celery",
  "Mushy peas",
  "Lemon",
  "Dill sauce",
  "Pastry",
  "Gravy",
  "Mushrooms",
  "Apple",
  "Grapes",
  "Walnuts",
  "Peas",
  "Sour cream",
];
